### ISSUE TITLE
Platform Support 

### ISSUE THREAD

**Issue by eamonburns** [ai-qol-things/rusty-ollama#18]
What platforms can I run this on? Does it work on Windows 11?

**Comment by Dax911** [comment]
It works on mac and linux as far as we have tested. I personally have no way of testing for windows. Also it relies on [ollama](https://github.com/jmorganca/ollama) which does not support Windows yet.

**Comment by eamonburns** [comment]
I am able to run the ollama server on Windows using [WSL](https://learn.microsoft.com/en-us/windows/wsl/about), so if all the command calls are replaced with API calls, then it *should* work. (API calls were mentioned in #19)

**Comment by eamonburns** [comment]
I was able to hack together a version that calls the API instead of the executable, and it works.
