### ISSUE TITLE
UI bugs - select model by default, enter / return should submit

### ISSUE THREAD

**Issue by sammcj** [ai-qol-things/rusty-ollama#21]
A few small bugs / tweaks that need fixing:

- [ ] A model should be loaded by default (probably?)
- [ ] Enter/return should submit a query
- [ ] Model output text should be clearly distinguishable from the main window UI element

**Comment by simoncollins** [comment]
Picking this one up.

**Comment by simoncollins** [comment]
Closing as this is complete now as of #34 .. can finesse the UI in a later ticket.
