### ISSUE TITLE
Integrate a global hotkey library for macOS to listen for the hotkey and activate the window.

### ISSUE THREAD

**Issue by sammcj** [ai-qol-things/rusty-ollama#9]
We will need to use a library that can register global hotkeys on macOS.

This library would listen for your specific hotkey combination and trigger the Tauri window to open.

An example of a similar use case is https://github.com/ahkohd/tauri-macos-spotlight-example

**Comment by simoncollins** [comment]
Hey @sammcj / @Dax911  ... I'll take a look at this one.

**Comment by sammcj** [comment]
pushed where I got to here: https://github.com/ai-qol-things/rusty-ollama/tree/spotlight1 but it may not be of value?

**Comment by simoncollins** [comment]
Raised https://github.com/ai-qol-things/rusty-ollama/pull/20 which adds this
